### ISSUE TITLE
🐛 [Bug] 초기 user nickname 설정 api Error

### ISSUE THREAD

**Issue by nyeoni** [GhostPangPang/GhostPong#247]
### Problem

42OAuth 로그인 후 -> 닉네임 설정 -> 에러!!!! 가 납니다.

### Reproduction

닉네임을 입력한 후 버튼을 누르면 됩니다.

### Screenshot

<img width="1478" alt="image" src="https://github.com/GhostPangPang/GhostPong/assets/51353146/c0cf2ae1-903d-4398-b998-b94dee4eeaa4">

### Expected Behavior

`auth` 로 잘 리다이렉트 시켜주면 됩니다. 

### Log

```Shell
error: error: invalid input syntax for type integer: "NaN"
[Nest] 21581  - 05/10/2023, 2:27:34 PM   ERROR [ExceptionsHandler] invalid input syntax for type integer: "NaN"
QueryFailedError: invalid input syntax for type integer: "NaN"
    at PostgresQueryRunner.query (/Users/chloek/project/GhostPong/backend/src/driver/postgres/PostgresQueryRunner.ts:299:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at SelectQueryBuilder.loadRawResults (/Users/chloek/project/GhostPong/backend/src/query-builder/SelectQueryBuilder.ts:3724:25)
    at SelectQueryBuilder.executeEntitiesAndRawResults (/Users/chloek/project/GhostPong/backend/src/query-builder/SelectQueryBuilder.ts:3487:26)
    at SelectQueryBuilder.getRawAndEntities (/Users/chloek/project/GhostPong/backend/src/query-builder/SelectQueryBuilder.ts:1661:29)
    at SelectQueryBuilder.getOne (/Users/chloek/project/GhostPong/backend/src/query-builder/SelectQueryBuilder.ts:1688:25)
    at UserService.checkAlreadyExistUser (/Users/chloek/project/GhostPong/backend/src/user/user.service.ts:107:9)
    at UserService.createUser (/Users/chloek/project/GhostPong/backend/src/user/user.service.ts:46:5)
    at UserController.createUser (/Users/chloek/project/GhostPong/backend/src/user/user.controller.ts:79:19)
    at /Users/chloek/project/GhostPong/backend/node_modules/@nestjs/core/router/router-execution-context.js:46:28
```

### Browser

Chrome

**Comment by Kimhan-nah** [comment]
'development'에서는 header의 'x-my-id'를, 'production'에서는 header의 'Authorization'을 사용하게 되는데요
기존에는 .env 파일에서 `NODE_ENV`를 수정했어야 됐는데, `yarn start:dev`와 `yarn start:prod` script 실행하도록 수정했습니다!

**Comment by nyeoni** [comment]
백엔드에서 `NODE_ENV=production` 모드와 `cors` 설정을 해주어서 해결되었습니다
